(function(w){"use strict";
var NS="__STREMIO_TIZENBREW_REMOTE__",VER="0.2.0",FOCUS="data-stremio-remote-focus",STYLE="data-stremio-remote-style",DIAG="data-stremio-remote-diagnostics-panel",BADGE="data-stremio-remote-boot-badge";
if(w[NS]&&w[NS].initialized)return;
var opt=["MediaPlayPause","MediaPlay","MediaPause","MediaStop","MediaFastForward","MediaRewind","ColorF0Red","ColorF1Green","ColorF2Yellow","ColorF3Blue","Info"];
var diag={Info:1,ColorF0Red:1,ColorF1Green:1,ColorF2Yellow:1,ColorF3Blue:1},media={MediaPlayPause:1,MediaPlay:1,MediaPause:1,MediaStop:1,MediaFastForward:1,MediaRewind:1},arrows={ArrowLeft:1,ArrowRight:1,ArrowUp:1,ArrowDown:1};
var code={13:"Enter",19:"MediaPause",27:"Back",32:"Enter",37:"ArrowLeft",38:"ArrowUp",39:"ArrowRight",40:"ArrowDown",403:"ColorF0Red",404:"ColorF1Green",405:"ColorF2Yellow",406:"ColorF3Blue",412:"MediaRewind",413:"MediaStop",415:"MediaPlay",417:"MediaFastForward",457:"Info",10009:"Back",10252:"MediaPlayPause"};
var alias={Left:"ArrowLeft",Right:"ArrowRight",Up:"ArrowUp",Down:"ArrowDown",Return:"Back",Escape:"Back",Backspace:"Back",XF86Back:"Back",BrowserBack:"Back",Play:"MediaPlay",Pause:"MediaPause",FastForward:"MediaFastForward",Rewind:"MediaRewind",Red:"ColorF0Red",Green:"ColorF1Green",Yellow:"ColorF2Yellow",Blue:"ColorF3Blue",Info:"Info"};
var sel={card:["a[href*='#/detail']","a[href*='#/discover']","a[href*='#/continuewatching']","a[class*='meta-item']","[class*='meta-item'][tabindex]"],rail:["nav[class*='vertical-nav-bar'] a","[class*='vertical-nav-bar'] a","[class*='nav-tab-button']"],search:["[class*='search-input']","[class*='search-bar'] input","[class*='search-bar'] [role='textbox']","input[placeholder*='Search']","input[placeholder*='search']"],searchBtn:["[class*='search-bar'] [class*='submit-button']","[class*='submit-button']"],top:["[class*='horizontal-nav-bar'] [class*='buttons-container'] [class*='button-container']","[class*='buttons-container'] [title*='fullscreen']","[class*='buttons-container'] [class*='menu-button']","[title*='fullscreen']","[class*='menu-button']","[class*='nav-menu-popup-label']"],menu:["[role='menu'] [role='menuitem']","[class*='menu'] [tabindex]","[class*='popup'] [tabindex]","[class*='dropdown'] [tabindex]"]};
var st={initialized:false,version:VER,registeredKeys:[],failedKeys:[],listenerPaths:[],diagnosticsOpen:false,bootBadgeShown:false,currentRole:"",currentText:"",lastKey:null,lastAction:null,lastConsumedAction:null,lastSpatialResult:null,lastPlayerActionResult:null,lastBackResolution:null,lastIgnoredReason:null,lastCounts:{},apiAvailability:{}};
var cur=null,lastSig="",lastAt=0,lastNav=0;
function d(){return w&&w.document?w.document:null}
function n(){return Date.now?Date.now():(new Date()).getTime()}
function a(e,k,v){if(e&&e.setAttribute)e.setAttribute(k,String(v))}
function ga(e,k){return e&&e.getAttribute?e.getAttribute(k):null}
function ra(e,k){if(e&&e.removeAttribute)e.removeAttribute(k)}
function m(e,s){try{return !!(e&&e.matches&&e.matches(s))}catch(_){return false}}
function cl(e,list){var x=e,i;while(x){for(i=0;i<list.length;i++)if(m(x,list[i]))return x;x=x.parentNode||null}return null}
function r(e){var x,L,T,W,H;if(!e||!e.getBoundingClientRect)return{left:0,top:0,right:0,bottom:0,width:0,height:0,cx:0,cy:0};x=e.getBoundingClientRect();L=+x.left||0;T=+x.top||0;W=+x.width||0;H=+x.height||0;return{left:L,top:T,right:L+W,bottom:T+H,width:W,height:H,cx:L+W/2,cy:T+H/2}}
function vis(e){var q,cs;if(!e||m(e,"script,style,template,[hidden],[disabled],[aria-hidden='true'],["+DIAG+"],["+DIAG+"] *,["+BADGE+"]"))return false;q=r(e);if(q.width<4||q.height<4)return false;try{cs=w.getComputedStyle&&w.getComputedStyle(e);if(cs&&(cs.display==="none"||cs.visibility==="hidden"||+cs.opacity===0))return false}catch(_){}return true}
function q(list){var doc=d(),out=[],seen=[],nodes,i,j,e;if(!doc||!doc.querySelectorAll)return out;for(i=0;i<list.length;i++)try{nodes=doc.querySelectorAll(list[i]);for(j=0;j<nodes.length;j++){e=nodes[j];if(seen.indexOf(e)<0&&vis(e)){seen.push(e);out.push(e)}}}catch(_){}out.sort(function(x,y){var X=r(x),Y=r(y);return Math.abs(X.cy-Y.cy)>24?X.cy-Y.cy:X.cx-Y.cx});return out}
function role(e){return cl(e,sel.card)?"card":cl(e,sel.rail)?"rail":cl(e,sel.searchBtn)?"search-button":cl(e,sel.search)?"search":cl(e,sel.top)?"top-button":cl(e,sel.menu)?"menu":m(e,"video,[class*='player'],[class*='video']")?"player":(e&&e.tagName||"element").toLowerCase()}
function txt(e){return String((e&&(ga(e,"aria-label")||ga(e,"title")||ga(e,"placeholder")||e.textContent||e.value))||"").replace(/\s+/g," ").replace(/^\s+|\s+$/g,"").slice(0,80)}
function active(){var doc=d(),e=doc&&doc.activeElement;if(!e||e===doc.body||e===doc.documentElement)e=cur||e;return cl(e,sel.card)||cl(e,sel.rail)||cl(e,sel.searchBtn)||cl(e,sel.search)||cl(e,sel.top)||cl(e,sel.menu)||e}
function f(e,why){if(!e||!vis(e)){st.lastIgnoredReason="no-target:"+why;return false}if(cur&&cur!==e)ra(cur,FOCUS);cur=e;if(ga(e,"tabindex")===null&&!m(e,"a[href],button,input,textarea,select,[tabindex]"))a(e,"tabindex","0");a(e,FOCUS,"true");st.currentRole=role(e);st.currentText=txt(e);st.lastSpatialResult=why;st.lastConsumedAction="spatial:"+why;try{e.focus({preventScroll:true})}catch(_){try{e.focus()}catch(__){}}try{e.scrollIntoView({block:"nearest",inline:"nearest"})}catch(_){}render();return true}
function counts(){st.lastCounts={cards:q(sel.card).length,rail:q(sel.rail).length,search:q(sel.search).length,searchBtn:q(sel.searchBtn).length,top:q(sel.top).length,menu:q(sel.menu).length};return st.lastCounts}
function best(items,ref,filter,score){var R=r(ref),b=null,bs=1/0,i,it,ir,s;for(i=0;i<items.length;i++){it=items[i];if(it===ref)continue;ir=r(it);if(filter&&!filter(ir,R,it))continue;s=score(ir,R,it);if(s<bs){bs=s;b=it}}return b}
function cardDir(c,dir){var cards=q(sel.card),tol=Math.max(72,r(c).height*.65);if(dir==="up")return best(cards,c,function(x,y){return x.cy<y.cy-20},function(x,y){return(y.cy-x.cy)*1000+Math.abs(y.cx-x.cx)});if(dir==="down")return best(cards,c,function(x,y){return x.cy>y.cy+20},function(x,y){return(x.cy-y.cy)*1000+Math.abs(y.cx-x.cx)});if(dir==="left")return best(cards,c,function(x,y){return x.cx<y.cx-20&&Math.abs(x.cy-y.cy)<=tol},function(x,y){return(y.cx-x.cx)*1000+Math.abs(y.cy-x.cy)});if(dir==="right")return best(cards,c,function(x,y){return x.cx>y.cx+20&&Math.abs(x.cy-y.cy)<=tol},function(x,y){return(x.cx-y.cx)*1000+Math.abs(y.cy-x.cy)});return null}
function nearRail(ref){var rail=q(sel.rail);return best(rail,ref,null,function(x,y){return Math.abs(x.cy-y.cy)*1000+Math.abs(x.cx-y.cx)})||rail[0]||null}
function nearCard(ref){var cards=q(sel.card);return best(cards,ref,function(x,y){return x.cx>y.cx+20},function(x,y){return Math.abs(x.cy-y.cy)*1000+Math.abs(x.cx-y.cx)})||cards[0]||null}
function first(list){return q(list)[0]||null}
function topNear(ref){var cards=q(sel.card),R=r(ref);return best(cards,ref,null,function(x){return Math.max(0,x.cy-R.cy)*1000+Math.abs(x.cx-R.cx)})||cards[0]||null}
function adjTop(e,dir){var buttons=q(sel.top),tb=cl(e,sel.top),i;for(i=0;i<buttons.length;i++)if(buttons[i]===tb)return dir==="left"?(buttons[i-1]||first(sel.searchBtn)||first(sel.search)):(buttons[i+1]||null);return buttons[0]||null}
function spatial(k){var e=active(),c=cl(e,sel.card),rail=cl(e,sel.rail),s=cl(e,sel.search),sb=cl(e,sel.searchBtn),tb=cl(e,sel.top),menu=cl(e,sel.menu),t;counts();if(!e||role(e)==="player"){st.lastIgnoredReason="player-or-empty";return false}if(menu){st.lastIgnoredReason="menu-pass-through";return false}
 if(c){if(k==="ArrowUp"){t=cardDir(c,"up")||first(sel.searchBtn)||first(sel.search);return t?f(t,"card-up"):false}if(k==="ArrowDown"){t=cardDir(c,"down");return t?f(t,"card-down"):false}if(k==="ArrowLeft"){t=cardDir(c,"left")||nearRail(c);return t?f(t,"card-left"):false}if(k==="ArrowRight"){t=cardDir(c,"right");return t?f(t,"card-right"):false}}
 if(rail){if(k==="ArrowRight"){t=nearCard(rail)||first(sel.search);return t?f(t,"rail-right"):false}st.lastIgnoredReason="rail-native";return false}
 if(s){if(k==="ArrowRight"){t=first(sel.searchBtn)||first(sel.top);return t?f(t,"search-right"):false}if(k==="ArrowDown"){t=topNear(s);return t?f(t,"search-down"):false}if(k==="ArrowLeft"){t=nearRail(s);return t?f(t,"search-left-rail"):false}}
 if(sb){if(k==="ArrowLeft"){t=first(sel.search);return t?f(t,"search-button-left"):false}if(k==="ArrowRight"){t=first(sel.top);return t?f(t,"search-button-right"):false}if(k==="ArrowDown"){t=topNear(sb);return t?f(t,"search-button-down"):false}if(k==="ArrowUp"){st.lastIgnoredReason="search-up-noop";return false}}
 if(tb){if(k==="ArrowLeft"){t=adjTop(tb,"left");return t?f(t,"top-left"):false}if(k==="ArrowRight"){t=adjTop(tb,"right");return t?f(t,"top-right"):false}if(k==="ArrowDown"){t=topNear(tb);return t?f(t,"top-down"):false}if(k==="ArrowUp"){st.lastIgnoredReason="top-up-noop";return false}}
 st.lastIgnoredReason="no-rule:"+k+":"+role(e);return false}
function norm(ev){var name=ev&&(ev.keyName||ev.key||ev.code),kc=ev&&(ev.keyCode||ev.which||ev.charCode),k=alias[name]||code[kc]||name||"";st.lastKey={normalizedKey:k,keyName:name||"",keyCode:kc||null,type:ev&&ev.type||""};return k}
function dupe(ev,k){var sig,t=n();if(!ev||ev.type==="tizenhwkey")return false;if(ev.type!=="keydown"){st.lastIgnoredReason="ignore-"+ev.type;return true}sig=ev.type+":"+k+":"+(ev.keyCode||ev.which||ev.code||ev.key||"");if(lastSig===sig&&t-lastAt<95){st.lastIgnoredReason="duplicate";return true}lastSig=sig;lastAt=t;return false}
function throttle(k){var t=n();if(!arrows[k])return false;if(t-lastNav<80){st.lastIgnoredReason="throttle";return true}lastNav=t;return false}
function consume(ev){if(ev&&ev.preventDefault)ev.preventDefault();if(ev&&ev.stopPropagation)ev.stopPropagation();if(ev&&ev.stopImmediatePropagation)ev.stopImmediatePropagation()}
function video(){var vids=q(["video"]),b=null,ba=-1,i,rr,A;for(i=0;i<vids.length;i++){rr=r(vids[i]);A=rr.width*rr.height;if(A>ba){b=vids[i];ba=A}}return b}
function control(action){var v=video(),before,dur;if(!v){st.lastPlayerActionResult=action+":no-video";render();return false}before=v.currentTime;try{if(action==="MediaPlayPause"){if(v.paused&&v.play)v.play();else if(v.pause)v.pause()}else if(action==="MediaPlay"&&v.play)v.play();else if(action==="MediaPause"&&v.pause)v.pause();else if(action==="MediaStop"){if(v.pause)v.pause();v.currentTime=0}else if(action==="MediaFastForward"||action==="MediaRewind"){dur=typeof v.duration==="number"&&isFinite(v.duration)?v.duration:null;v.currentTime=Math.max(0,Math.min(dur||Number.MAX_SAFE_INTEGER,before+(action==="MediaFastForward"?15:-15)))}st.lastPlayerActionResult=action+":ok";render();return true}catch(e){st.lastPlayerActionResult=action+":error:"+(e&&e.message?e.message:String(e));render();return false}}
function esc(){var ev;if(!d()||!w.KeyboardEvent)return false;try{ev=new w.KeyboardEvent("keydown",{key:"Escape",code:"Escape",bubbles:true,cancelable:true});d().dispatchEvent(ev);return true}catch(_){return false}}
function back(){var v;if(st.diagnosticsOpen){st.diagnosticsOpen=false;st.lastBackResolution="closed-diagnostics";render();return true}v=video();if(v){try{if(v.pause)v.pause()}catch(_){}if(esc()){st.lastBackResolution="player-escape";render();return true}}try{if(w.history&&w.history.length>1&&w.history.back){w.history.back();st.lastBackResolution="history-back";render();return true}}catch(_){}st.lastBackResolution="passed-through";render();return false}
function css(){var doc=d(),style;if(!doc||!doc.head||!doc.createElement)return false;if(doc.querySelector&&doc.querySelector("style["+STYLE+"='1']"))return true;style=doc.createElement("style");style.type="text/css";a(style,STYLE,"1");style.appendChild(doc.createTextNode("["+FOCUS+"='true']{outline:3px solid #20c997!important;outline-offset:3px!important;border-radius:6px}["+DIAG+"='1']{position:fixed;top:14px;right:14px;z-index:2147483647;width:min(560px,calc(100vw - 28px));max-height:calc(100vh - 28px);overflow:auto;padding:12px 14px;border:1px solid rgba(32,201,151,.6);border-radius:10px;background:rgba(5,10,18,.94);color:#f4fff9;font:12px/1.45 Consolas,'Courier New',monospace;white-space:pre-wrap;display:none}["+DIAG+"='1'][data-open='true']{display:block}["+BADGE+"='1']{position:fixed;left:14px;bottom:14px;z-index:2147483645;padding:8px 10px;border-radius:8px;background:rgba(5,10,18,.88);color:#f4fff9;font:12px/1.3 system-ui,sans-serif;border:1px solid rgba(32,201,151,.45)}"));doc.head.appendChild(style);return true}
function badge(){var doc=d(),b;if(!doc||!doc.body||!doc.createElement)return false;if(doc.querySelector&&doc.querySelector("["+BADGE+"='1']"))return true;b=doc.createElement("div");a(b,BADGE,"1");b.textContent="Stremio Remote "+VER+" loaded";doc.body.appendChild(b);st.bootBadgeShown=true;if(w.setTimeout)w.setTimeout(function(){if(b&&b.parentNode)b.parentNode.removeChild(b)},4200);return true}
function reg(){var tz=w&&w.tizen,input=tz&&(tz.tvinputdevice||tz.inputdevice),i,k;st.registeredKeys=[];st.failedKeys=[];st.apiAvailability={document:!!d(),documentBody:!!(d()&&d().body),tizen:!!tz,tvInputDevice:!!(input&&input.registerKey),application:!!(tz&&tz.application&&tz.application.getCurrentApplication)};if(!input||!input.registerKey)return[];for(i=0;i<opt.length;i++){k=opt[i];try{input.registerKey(k);st.registeredKeys.push(k)}catch(e){st.failedKeys.push({keyName:k,message:e&&e.message?e.message:String(e)})}}return st.registeredKeys.slice()}
function panel(){var doc=d(),p;if(!doc||!doc.body||!doc.createElement)return null;p=doc.querySelector&&doc.querySelector("["+DIAG+"='1']");if(!p){p=doc.createElement("pre");a(p,DIAG,"1");doc.body.appendChild(p)}return p}
function render(){var p=panel();counts();if(!p)return false;a(p,"data-open",st.diagnosticsOpen?"true":"false");a(p,"aria-hidden",st.diagnosticsOpen?"false":"true");p.textContent=["Stremio Web TV Remote Diagnostics","Version: "+VER,"Current: "+(st.currentRole||"(none)")+" "+(st.currentText||""),"Last key: "+(st.lastKey?st.lastKey.normalizedKey:"(none)"),"Last action: "+(st.lastAction||"(none)"),"Last consumed: "+(st.lastConsumedAction||"(none)"),"Last spatial: "+(st.lastSpatialResult||"(none)"),"Last ignored: "+(st.lastIgnoredReason||"(none)"),"Last player: "+(st.lastPlayerActionResult||"(none)"),"Last back: "+(st.lastBackResolution||"(none)"),"Counts: cards="+st.lastCounts.cards+", rail="+st.lastCounts.rail+", search="+st.lastCounts.search+", searchBtn="+st.lastCounts.searchBtn+", top="+st.lastCounts.top+", menu="+st.lastCounts.menu,"Registered: "+(st.registeredKeys.join(", ")||"(none)"),"Failed: "+(st.failedKeys.map(function(x){return x.keyName+":"+x.message}).join(", ")||"(none)"),"Listeners: "+st.listenerPaths.join(", ")].join("\n");return true}
function handler(ev,path){var k;st.lastRawEvent={path:path,type:ev&&ev.type||"",key:ev&&ev.key||"",code:ev&&ev.code||"",keyCode:ev&&ev.keyCode||null,which:ev&&ev.which||null,keyName:ev&&ev.keyName||""};k=norm(ev);st.lastAction="key:"+k;if(dupe(ev,k))return false;if(diag[k]){st.diagnosticsOpen=!st.diagnosticsOpen;st.lastConsumedAction=st.diagnosticsOpen?"diagnostics:open":"diagnostics:close";render();consume(ev);return true}if(arrows[k]){if(!throttle(k)&&spatial(k)){consume(ev);return true}render();return false}if(k==="Enter"&&cur&&cur.click){st.lastConsumedAction="spatial:enter-click";cur.click();consume(ev);render();return true}if(media[k]){if(control(k)){consume(ev);return true}return false}if(k==="Back"&&back()){consume(ev);return true}render();return false}
function listen(t,ev,path){if(!t||!t.addEventListener)return false;t.addEventListener(ev,function(e){handler(e,path+":"+ev)},true);st.listenerPaths.push(path+":"+ev);return true}
function init(){if(st.initialized)return;css();reg();listen(d(),"keydown","document");listen(d(),"tizenhwkey","document");listen(w,"keydown","window");listen(w,"tizenhwkey","window");st.initialized=true;w[NS]=api;badge();render()}
var api={initialized:false,version:VER,getState:function(){counts();return JSON.parse(JSON.stringify(st))},openDiagnostics:function(){st.diagnosticsOpen=true;return render()},closeDiagnostics:function(){st.diagnosticsOpen=false;return render()},toggleDiagnostics:function(){st.diagnosticsOpen=!st.diagnosticsOpen;return render()},focusSearch:function(){return f(first(sel.search)||first(sel.searchBtn),"api-focus-search")},focusFirstCard:function(){return f(first(sel.card),"api-focus-first-card")},focusRail:function(){return f(first(sel.rail),"api-focus-rail")},controlVideo:control};
w[NS]=api;if(d()&&(d().readyState==="interactive"||d().readyState==="complete"))init();else if(d()&&d().addEventListener){d().addEventListener("DOMContentLoaded",init,false);if(w.setTimeout)w.setTimeout(init,1500)}else init();api.initialized=true})(typeof window!=="undefined"?window:this);
