(function (window) {
  "use strict";
  var NS = "__STREMIO_TIZENBREW_REMOTE__";
  var VERSION = "0.2.9";
  var DIAG = "data-stremio-remote-diagnostics-panel";
  var STYLE = "data-stremio-remote-style";
  var FOCUS = "data-stremio-remote-player-focus";
  var TVFOCUS = "data-stremio-tv-focus";
  var LOCK = "data-stremio-player-overlay-locked";
  var FALLBACK = "data-stremio-remote-player-overlay";
  var SEEK_SECONDS = 15;
  var SEEK_PREVIEW_MS = 3500;

  if (window[NS] && window[NS].initialized) return;

  var optionalKeys = ["MediaPlayPause", "MediaPlay", "MediaPause", "MediaStop", "MediaFastForward", "MediaRewind", "ColorF0Red", "ColorF1Green", "ColorF2Yellow", "ColorF3Blue", "Info"];
  var diagnosticsKeys = { Info: true, ColorF0Red: true, ColorF1Green: true, ColorF2Yellow: true, ColorF3Blue: true };
  var mediaKeys = { MediaPlayPause: true, MediaPlay: true, MediaPause: true, MediaStop: true, MediaFastForward: true, MediaRewind: true };
  var arrowKeys = { ArrowLeft: true, ArrowRight: true, ArrowUp: true, ArrowDown: true };
  var keyCodeMap = { 8: "Back", 13: "Enter", 19: "MediaPause", 27: "Back", 32: "Enter", 37: "ArrowLeft", 38: "ArrowUp", 39: "ArrowRight", 40: "ArrowDown", 403: "ColorF0Red", 404: "ColorF1Green", 405: "ColorF2Yellow", 406: "ColorF3Blue", 412: "MediaRewind", 413: "MediaStop", 415: "MediaPlay", 417: "MediaFastForward", 457: "Info", 10009: "Back", 10252: "MediaPlayPause" };
  var keyAliasMap = { Back: "Back", Return: "Back", Escape: "Back", Backspace: "Back", XF86Back: "Back", BrowserBack: "Back", Play: "MediaPlay", Pause: "MediaPause", FastForward: "MediaFastForward", Rewind: "MediaRewind", Left: "ArrowLeft", Right: "ArrowRight", Up: "ArrowUp", Down: "ArrowDown", ArrowLeft: "ArrowLeft", ArrowRight: "ArrowRight", ArrowUp: "ArrowUp", ArrowDown: "ArrowDown" };

  var state = { initialized: false, version: VERSION, diagnosticsOpen: false, overlayLocked: false, overlayMode: "none", registeredKeys: [], failedKeys: [], lastKey: "", lastAction: "", lastIgnored: "", lastBack: "", lastPlayer: "", lastOverlay: "", lastSeek: "", lastSpatial: "", lastSpatialTarget: "", focusedControlIndex: -1, lastFocusedControl: "" };
  var tvFocus = null;
  var focusedControl = null;
  var seekPreviewTimer = null;
  var lastSpatialAt = 0;

  var cardSelectors = ["a[href*='#/detail']", "a[href*='/detail']", "a[href*='#/discover']", "a[class*='meta-item']", "[class*='meta-item'][tabindex]", "[class*='poster'][tabindex]", "[class*='Poster'][tabindex]"];
  var railSelectors = ["nav[class*='vertical-nav-bar'] a", "[class*='vertical-nav-bar'] a", "[class*='nav-tab-button']", "[class*='side'] a", "[class*='Side'] a", "[class*='nav'] a[href]"];
  var streamSelectors = ["[class*='stream']", "[class*='Stream']", "[class*='addon']", "[class*='Addon']", "[class*='source']", "[class*='Source']", "[role='listitem']", "[class*='list-item']", "[class*='ListItem']", "[class*='row']", "[class*='Row']", "[tabindex]"];
  var selectedSelectors = ["[" + TVFOCUS + "='true']", "[aria-selected='true']", "[class*='focused']", "[class*='Focused']", "[class*='selected']", "[class*='Selected']", "[class*='active']", "[class*='Active']"];

  function bodyText() { return document && document.body ? String(document.body.textContent || "").toLowerCase() : ""; }
  function isDetailPage() { var t = bodyText(), h = window.location ? String(window.location.hash || "").toLowerCase() : ""; return h.indexOf("detail") >= 0 || (t.indexOf("summary") >= 0 && t.indexOf("genres") >= 0); }
  function isLoadingStreams() { var t = bodyText(); return t.indexOf("addons are still loading") >= 0 || t.indexOf("add-ons are still loading") >= 0 || (t.indexOf("loading") >= 0 && t.indexOf("addon") >= 0); }
  function hasUnsupportedVideoText() { var t = bodyText(); return t.indexOf("video is not supported") >= 0 || (t.indexOf("not supported") >= 0 && t.indexOf("video") >= 0); }

  function rect(el) { var r, l, t, w, h; if (!el || !el.getBoundingClientRect) return { left: 0, top: 0, right: 0, bottom: 0, width: 0, height: 0, cx: 0, cy: 0 }; r = el.getBoundingClientRect(); l = +r.left || 0; t = +r.top || 0; w = +r.width || 0; h = +r.height || 0; return { left: l, top: t, right: l + w, bottom: t + h, width: w, height: h, cx: l + w / 2, cy: t + h / 2 }; }
  function own(el) { return !!(el && el.closest && el.closest("[" + DIAG + "='1'],[" + FALLBACK + "='1']")); }
  function visible(el) { var r, s; if (!el || !el.getBoundingClientRect || own(el)) return false; r = rect(el); if (r.width < 4 || r.height < 4) return false; try { s = window.getComputedStyle(el); if (s && (s.display === "none" || s.visibility === "hidden" || Number(s.opacity) === 0)) return false; } catch (_e) {} return true; }
  function textOf(el) { return String(el && ((el.getAttribute && (el.getAttribute("aria-label") || el.getAttribute("title") || el.getAttribute("placeholder"))) || el.textContent || el.value) || "").replace(/\s+/g, " ").replace(/^\s+|\s+$/g, "").slice(0, 120); }
  function classText(el) { return String(el && (el.className || el.id || "") || "").toLowerCase(); }
  function matchesAny(el, selectors) { var i; for (i = 0; i < selectors.length; i += 1) { try { if (el && el.matches && el.matches(selectors[i])) return true; } catch (_e) {} } return false; }
  function closestAny(el, selectors) { var cur = el, i; while (cur) { for (i = 0; i < selectors.length; i += 1) { try { if (cur.matches && cur.matches(selectors[i])) return cur; } catch (_e) {} } cur = cur.parentNode; } return null; }
  function sortPos(a, b) { var ar = rect(a), br = rect(b); if (Math.abs(ar.cy - br.cy) > 24) return ar.cy - br.cy; return ar.cx - br.cx; }
  function q(selectors, filter) { var out = [], seen = [], nodes, i, j, el; if (!document.querySelectorAll) return out; for (i = 0; i < selectors.length; i += 1) { try { nodes = document.querySelectorAll(selectors[i]); for (j = 0; j < nodes.length; j += 1) { el = nodes[j]; if (seen.indexOf(el) < 0 && visible(el) && (!filter || filter(el))) { seen.push(el); out.push(el); } } } catch (_e) {} } return out.sort(sortPos); }

  function looksLikeCard(el) { var r = rect(el), c = classText(el), t = textOf(el).toLowerCase(); if (closestAny(el, railSelectors)) return false; if (r.width < 60 || r.height < 40) return false; return matchesAny(el, cardSelectors) || /meta|poster|card|movie|series|item/.test(c) || (/watch|season|episode/.test(t) && r.width < 900); }
  function cards() { return q(cardSelectors.concat(["[tabindex]", "a[href]"]), looksLikeCard); }
  function rails() { var leftLimit = (window.innerWidth || 1920) * 0.30; return q(railSelectors, function (el) { var r = rect(el), t = textOf(el).toLowerCase(), c = classText(el); return r.cx < leftLimit && r.width >= 18 && r.height >= 14 && (/discover|library|settings|search|home|board|calendar|addons|add-ons/.test(t + c) || matchesAny(el, railSelectors)); }); }
  function streamText(t) { t = String(t || "").toLowerCase(); return /2160p|1080p|720p|480p|4k|hdr|dv|remux|webdl|webrip|bluray|brrip|x265|x264|h264|h265|gb|mb|seed|⚡|english|ingl|portugu|french|italian|polish|hindi|czech|torrent|stream/.test(t); }
  function looksLikeStream(el) { var r = rect(el), right = r.left > ((window.innerWidth || 1920) * 0.34) || r.cx > ((window.innerWidth || 1920) * 0.5), t = textOf(el), c = classText(el); if (!isDetailPage() || closestAny(el, railSelectors)) return false; return right && r.width > 70 && r.height > 14 && r.height < 280 && (/stream|addon|source|torrent|row|list|provider/.test(c) || streamText(t)); }
  function streams() { return q(streamSelectors, looksLikeStream); }
  function roleOf(el) { if (!el) return "none"; if (closestAny(el, railSelectors)) return "rail"; if (looksLikeStream(el)) return "stream"; if (looksLikeCard(el)) return "card"; return (el.tagName || "element").toLowerCase(); }
  function selectedSpatial() { var items = cards().concat(streams()).concat(rails()), i, j, el; for (i = 0; i < items.length; i += 1) { el = items[i]; for (j = 0; j < selectedSelectors.length; j += 1) { try { if (el.matches && el.matches(selectedSelectors[j])) return el; if (closestAny(el, [selectedSelectors[j]])) return el; } catch (_e) {} } } return null; }
  function activeSpatial() { var el = document.activeElement; if (tvFocus && visible(tvFocus)) return tvFocus; if (el && el !== document.body && el !== document.documentElement && visible(el)) return closestAny(el, railSelectors) || el; return selectedSpatial(); }
  function setTvFocus(el, reason) { if (!el || !visible(el)) { state.lastSpatial = "no-target:" + reason; return false; } if (tvFocus && tvFocus !== el && tvFocus.removeAttribute) tvFocus.removeAttribute(TVFOCUS); tvFocus = el; if (el.getAttribute && el.getAttribute("tabindex") === null && el.setAttribute) el.setAttribute("tabindex", "0"); if (el.setAttribute) el.setAttribute(TVFOCUS, "true"); try { el.focus({ preventScroll: true }); } catch (_e) { try { el.focus(); } catch (_e2) {} } try { el.scrollIntoView({ block: "center", inline: "nearest", behavior: "auto" }); } catch (_e3) {} state.lastSpatial = reason; state.lastSpatialTarget = roleOf(el) + ":" + textOf(el); return true; }

  function overlapY(a, b) { return Math.max(0, Math.min(a.bottom, b.bottom) - Math.max(a.top, b.top)); }
  function best(items, ref, filter, score) { var rr = rect(ref), bestEl = null, bestScore = Infinity, i, it, ir, s; for (i = 0; i < items.length; i += 1) { it = items[i]; if (it === ref) continue; ir = rect(it); if (filter && !filter(ir, rr, it)) continue; s = score(ir, rr, it); if (s < bestScore) { bestScore = s; bestEl = it; } } return bestEl; }
  function above(items, ref) { return best(items, ref, function (a, b) { return a.cy < b.cy - Math.max(32, b.height * 0.20); }, function (a, b) { return (b.cy - a.cy) * 1000 + Math.abs(b.cx - a.cx); }); }
  function below(items, ref) { return best(items, ref, function (a, b) { return a.cy > b.cy + Math.max(32, b.height * 0.20); }, function (a, b) { return (a.cy - b.cy) * 1000 + Math.abs(b.cx - a.cx); }); }
  function horizontal(items, ref, dir) { var rr = rect(ref), minOverlap = Math.max(18, Math.min(rr.height * 0.30, 90)); return best(items, ref, function (a, b) { var sameRow = overlapY(a, b) >= minOverlap || Math.abs(a.cy - b.cy) <= Math.max(90, b.height); if (!sameRow) return false; return dir < 0 ? a.cx < b.cx - 10 : a.cx > b.cx + 10; }, function (a, b) { return Math.abs(a.cx - b.cx) * 1000 + Math.abs(a.cy - b.cy); }); }
  function nearestRail(ref) { var rs = rails(); return best(rs, ref, null, function (a, b) { return Math.abs(a.cy - b.cy) * 1000 + Math.abs(a.cx - b.cx); }) || rs[0] || null; }
  function nearestCardFromRail(ref) { var cs = cards(); return best(cs, ref, function (a, b) { return a.cx > b.cx + 20; }, function (a, b) { return Math.abs(a.cy - b.cy) * 1000 + Math.abs(a.cx - b.cx); }) || cs[0] || null; }
  function nextInList(items, ref, delta) { var i = items.indexOf(ref); if (i < 0) return items[delta > 0 ? 0 : items.length - 1] || null; return items[Math.max(0, Math.min(items.length - 1, i + delta))] || items[i]; }

  function getVideos() { return Array.prototype.slice.call(document.querySelectorAll("video")); }
  function getPrimaryVideo() { var vids = getVideos(), best = null, bestArea = -1, i, r, a; for (i = 0; i < vids.length; i += 1) { r = rect(vids[i]); a = r.width * r.height; if ((visible(vids[i]) || vids[i].currentSrc || vids[i].src) && a >= bestArea) { best = vids[i]; bestArea = a; } } return best || vids[0] || null; }
  function isRealPlayer() { var v = getPrimaryVideo(), r, area, screen; if (!v) return false; r = rect(v); area = r.width * r.height; screen = (window.innerWidth || 1920) * (window.innerHeight || 1080); return visible(v) && area > screen * 0.12 && (v.currentSrc || v.src || v.readyState > 0 || v.currentTime > 0 || v.paused === false); }
  function hasPlayerVideo() { return isRealPlayer(); }

  function nonPlayerSpatial(key) { var now = Date.now(), el = activeSpatial(), role, items, target; if (!el || state.overlayLocked || hasPlayerVideo()) return false; if (now - lastSpatialAt < 70) return true; lastSpatialAt = now; role = roleOf(el); if (role === "rail") { items = rails(); if (key === "ArrowUp") target = nextInList(items, closestAny(el, railSelectors) || el, -1); else if (key === "ArrowDown") target = nextInList(items, closestAny(el, railSelectors) || el, 1); else if (key === "ArrowRight") target = nearestCardFromRail(el); else if (key === "ArrowLeft") { state.lastSpatial = "rail-left-noop"; return true; } return target ? setTvFocus(target, "rail-" + key.replace("Arrow", "").toLowerCase()) : false; } if (role === "stream") { items = streams(); if (key === "ArrowUp") target = above(items, el) || nextInList(items, el, -1); else if (key === "ArrowDown") target = below(items, el) || nextInList(items, el, 1); else if (key === "ArrowLeft") { state.lastSpatial = "stream-left-pass-through"; return false; } else return false; return target ? setTvFocus(target, "stream-" + key.replace("Arrow", "").toLowerCase()) : false; } if (role === "card") { items = cards(); if (key === "ArrowUp") target = above(items, el); else if (key === "ArrowDown") target = below(items, el); else if (key === "ArrowLeft") target = horizontal(items, el, -1) || nearestRail(el); else if (key === "ArrowRight") target = horizontal(items, el, 1); else return false; return target ? setTvFocus(target, "card-" + key.replace("Arrow", "").toLowerCase()) : false; } return false; }

  function looksLikePlayerControl(el) { var r = rect(el), c = classText(el), label = textOf(el).toLowerCase(), bottom = r.cy > ((window.innerHeight || 1080) * 0.42), anc = el.closest && el.closest("[class*='player'],[class*='Player'],[class*='control'],[class*='Control'],[class*='video'],[class*='Video']"), named = /play|pause|seek|audio|subtitle|caption|cast|volume|fullscreen|screen|speed|quality|settings|menu|more|back|next|previous|rewind|forward/.test(c + " " + label), roleBtn = el.getAttribute && (el.getAttribute("role") === "button" || el.getAttribute("tabindex") !== null); return bottom && (anc || named || roleBtn) && r.width >= 8 && r.height >= 8 && r.width <= 520 && r.height <= 240; }
  function getPlayerControls() { return q(["button", "[role='button']", "[tabindex]", "[aria-label]", "[title]"], looksLikePlayerControl); }
  function getPlayerDebug() { var vids = getVideos(), v = getPrimaryVideo(), src = v ? String(v.currentSrc || v.src || "") : "", err = "", controls = getPlayerControls(); if (v && v.error) err = "code=" + String(v.error.code || "") + " message=" + String(v.error.message || ""); return { count: vids.length, controls: controls.length, src: src.slice(0, 220), paused: v ? String(v.paused) : "null", readyState: v ? String(v.readyState) : "null", networkState: v ? String(v.networkState) : "null", currentTime: v && typeof v.currentTime === "number" ? String(Math.floor(v.currentTime)) : "null", duration: v && typeof v.duration === "number" && isFinite(v.duration) ? String(Math.floor(v.duration)) : "null", error: err || "none" }; }

  function ensureStyles() { var style; if (document.querySelector("style[" + STYLE + "='1']")) return; style = document.createElement("style"); style.setAttribute(STYLE, "1"); style.textContent = ["[" + DIAG + "='1']{position:fixed;top:14px;right:14px;z-index:2147483647;width:min(760px,calc(100vw - 28px));max-height:calc(100vh - 28px);overflow:auto;padding:12px 14px;border:1px solid rgba(32,201,151,.6);border-radius:10px;background:rgba(5,10,18,.94);color:#f4fff9;font:12px/1.45 Consolas,'Courier New',monospace;white-space:pre-wrap;display:none}", "[" + DIAG + "='1'][data-open='true']{display:block}", "html[" + LOCK + "='true'] [class*='player'],html[" + LOCK + "='true'] [class*='Player'],html[" + LOCK + "='true'] [class*='control'],html[" + LOCK + "='true'] [class*='Control'],html[" + LOCK + "='true'] [class*='seek'],html[" + LOCK + "='true'] [class*='Seek'],html[" + LOCK + "='true'] [class*='progress'],html[" + LOCK + "='true'] [class*='Progress']{opacity:1!important;visibility:visible!important;pointer-events:auto!important}", "html[" + LOCK + "='true'] button,html[" + LOCK + "='true'] [role='button'],html[" + LOCK + "='true'] [tabindex]{pointer-events:auto!important}", "[" + FOCUS + "='true'],[" + TVFOCUS + "='true']{outline:3px solid #20c997!important;outline-offset:3px!important;border-radius:6px!important}", "[" + FALLBACK + "='1']{position:fixed;left:50%;bottom:88px;transform:translateX(-50%);z-index:2147483646;padding:10px 14px;border-radius:10px;background:rgba(5,10,18,.88);color:#f4fff9;font:14px/1.4 system-ui,sans-serif;border:1px solid rgba(32,201,151,.5);display:none}", "html[" + LOCK + "='true'] [" + FALLBACK + "='1'][data-show='true']{display:block}"].join("\n"); document.head.appendChild(style); }
  function getPanel() { var p = document.querySelector("[" + DIAG + "='1']"); if (!p) { p = document.createElement("pre"); p.setAttribute(DIAG, "1"); document.body.appendChild(p); } return p; }
  function getFallbackOverlay() { var o = document.querySelector("[" + FALLBACK + "='1']"); if (!o) { o = document.createElement("div"); o.setAttribute(FALLBACK, "1"); document.body.appendChild(o); } return o; }
  function updateFallbackOverlay() { var o = getFallbackOverlay(), d = getPlayerDebug(); o.setAttribute("data-show", state.overlayLocked && d.controls === 0 ? "true" : "false"); o.textContent = state.overlayMode === "seek-preview" ? "Seeking: " + d.currentTime + " / " + d.duration + ". Press Left/Right to keep seeking." : "Paused. Controls found: " + d.controls + ". Press Play to resume or Back to close overlay."; }
  function renderDiagnostics() { var d = getPlayerDebug(), p = getPanel(); p.setAttribute("data-open", state.diagnosticsOpen ? "true" : "false"); p.textContent = ["Stremio Web TV Remote Diagnostics", "Version: " + VERSION, "Mode: player seek preview + fixed horizontal cards", "Real player: " + String(hasPlayerVideo()), "Overlay locked: " + String(state.overlayLocked), "Overlay mode: " + state.overlayMode, "Detail page: " + String(isDetailPage()), "Streams loading: " + String(isLoadingStreams()), "Video not supported text: " + String(hasUnsupportedVideoText()), "Last key: " + (state.lastKey || "none"), "Last action: " + (state.lastAction || "none"), "Last ignored: " + (state.lastIgnored || "none"), "Last spatial: " + (state.lastSpatial || "none"), "Spatial target: " + (state.lastSpatialTarget || "none"), "Last back: " + (state.lastBack || "none"), "Last player: " + (state.lastPlayer || "none"), "Last seek: " + (state.lastSeek || "none"), "Last overlay: " + (state.lastOverlay || "none"), "Focused control: " + (state.lastFocusedControl || "none"), "Videos: " + d.count + ", Controls: " + d.controls, "Video src: " + (d.src || "none"), "Video paused: " + d.paused, "Video time: " + d.currentTime + " / " + d.duration, "Video readyState: " + d.readyState, "Video networkState: " + d.networkState, "Video error: " + d.error, "Registered: " + (state.registeredKeys.join(", ") || "none"), "Failed: " + (state.failedKeys.map(function (i) { return i.keyName + ":" + i.message; }).join(", ") || "none")].join("\n"); updateFallbackOverlay(); }
  function registerOptionalKeys() { var input = window.tizen && (window.tizen.tvinputdevice || window.tizen.inputdevice), i; if (!input || !input.registerKey) return; for (i = 0; i < optionalKeys.length; i += 1) { try { input.registerKey(optionalKeys[i]); state.registeredKeys.push(optionalKeys[i]); } catch (e) { state.failedKeys.push({ keyName: optionalKeys[i], message: e && e.message ? e.message : String(e) }); } } }
  function normalizeKey(event) { var raw = event && (event.keyName || event.key || event.code) || ""; return keyAliasMap[raw] || keyCodeMap[event && event.keyCode] || raw; }
  function consume(event) { if (event && event.preventDefault) event.preventDefault(); if (event && event.stopPropagation) event.stopPropagation(); if (event && event.stopImmediatePropagation) event.stopImmediatePropagation(); }

  function revealNativeOverlay() { var v = getPrimaryVideo(), ev; try { ev = new MouseEvent("mousemove", { bubbles: true, cancelable: true, clientX: Math.floor((window.innerWidth || 1920) / 2), clientY: Math.floor((window.innerHeight || 1080) - 90) }); if (v) v.dispatchEvent(ev); document.dispatchEvent(ev); document.body.dispatchEvent(ev); state.lastOverlay = "mousemove + css-lock"; return true; } catch (_e) { state.lastOverlay = "css-lock-only"; return false; } }
  function clearSeekPreviewTimer() { if (seekPreviewTimer) { window.clearTimeout(seekPreviewTimer); seekPreviewTimer = null; } }
  function unlockOverlay(reason) { var root = document.documentElement; clearSeekPreviewTimer(); state.overlayLocked = false; state.overlayMode = "none"; if (root && root.removeAttribute) root.removeAttribute(LOCK); if (focusedControl && focusedControl.removeAttribute) focusedControl.removeAttribute(FOCUS); focusedControl = null; state.focusedControlIndex = -1; state.lastFocusedControl = ""; state.lastOverlay = reason || "unlock-overlay"; renderDiagnostics(); }
  function lockOverlay(mode, reason) { var root = document.documentElement; clearSeekPreviewTimer(); state.overlayLocked = true; state.overlayMode = mode || "paused-controls"; if (root && root.setAttribute) root.setAttribute(LOCK, "true"); revealNativeOverlay(); if (state.overlayMode === "paused-controls") focusPlayerControl(0, reason || "lock-overlay"); renderDiagnostics(); }
  function scheduleSeekPreviewUnlock() { clearSeekPreviewTimer(); seekPreviewTimer = window.setTimeout(function () { var v = getPrimaryVideo(); if (state.overlayMode === "seek-preview" && v && !v.paused) unlockOverlay("seek-preview-timeout"); }, SEEK_PREVIEW_MS); }
  function focusPlayerControl(index, reason) { var controls = getPlayerControls(), control; if (!controls.length) { state.focusedControlIndex = -1; state.lastFocusedControl = "none"; state.lastOverlay = reason + ":no-controls"; return false; } index = Math.max(0, Math.min(controls.length - 1, index)); if (focusedControl && focusedControl.removeAttribute) focusedControl.removeAttribute(FOCUS); control = controls[index]; focusedControl = control; state.focusedControlIndex = index; state.lastFocusedControl = textOf(control) || control.tagName || "control"; state.lastOverlay = reason; if (control.getAttribute && control.getAttribute("tabindex") === null && control.setAttribute) control.setAttribute("tabindex", "0"); if (control.setAttribute) control.setAttribute(FOCUS, "true"); try { control.focus({ preventScroll: true }); } catch (_e) { try { control.focus(); } catch (_e2) {} } return true; }
  function movePlayerFocus(direction) { var controls = getPlayerControls(), nextIndex; if (!state.overlayLocked || state.overlayMode !== "paused-controls") return false; if (!controls.length) { state.lastPlayer = "player-controls:none"; renderDiagnostics(); return true; } nextIndex = state.focusedControlIndex; if (nextIndex < 0 || !focusedControl) nextIndex = 0; if (direction === "left") nextIndex = Math.max(0, nextIndex - 1); if (direction === "right") nextIndex = Math.min(controls.length - 1, nextIndex + 1); if (direction === "up" || direction === "down") { state.lastPlayer = "player-" + direction + ":kept-overlay"; renderDiagnostics(); return true; } focusPlayerControl(nextIndex, "player-focus-" + direction); state.lastPlayer = "player-focus-" + direction; renderDiagnostics(); return true; }
  function clickFocusedControl() { if (!state.overlayLocked || state.overlayMode !== "paused-controls" || !focusedControl) return false; try { focusedControl.click(); state.lastPlayer = "clicked-control:" + (textOf(focusedControl) || focusedControl.tagName || "control"); renderDiagnostics(); return true; } catch (e) { state.lastPlayer = "click-control-error:" + (e && e.message ? e.message : String(e)); renderDiagnostics(); return true; } }
  function pauseAndLockOverlay(action) { var v = getPrimaryVideo(); if (!v) { state.lastPlayer = action + ":no-video"; renderDiagnostics(); return false; } try { if (v.pause) v.pause(); state.lastPlayer = action + ":pause-lock-overlay"; lockOverlay("paused-controls", action); return true; } catch (e) { state.lastPlayer = action + ":error:" + (e && e.message ? e.message : String(e)); renderDiagnostics(); return false; } }
  function playAndUnlockOverlay(action) { var v = getPrimaryVideo(); if (!v) { state.lastPlayer = action + ":no-video"; renderDiagnostics(); return false; } try { if (v.play) v.play(); state.lastPlayer = action + ":play-unlock-overlay"; unlockOverlay(action); return true; } catch (e) { state.lastPlayer = action + ":error:" + (e && e.message ? e.message : String(e)); renderDiagnostics(); return false; } }
  function seekVideo(action, delta, previewMode) { var v = getPrimaryVideo(), duration, before; if (!v) { state.lastPlayer = action + ":no-video"; renderDiagnostics(); return false; } try { before = typeof v.currentTime === "number" ? v.currentTime : 0; duration = typeof v.duration === "number" && isFinite(v.duration) ? v.duration : Number.MAX_SAFE_INTEGER; v.currentTime = Math.max(0, Math.min(duration, before + delta)); state.lastPlayer = action + ":seek"; state.lastSeek = Math.floor(before) + " -> " + Math.floor(v.currentTime); if (previewMode) { lockOverlay("seek-preview", action); scheduleSeekPreviewUnlock(); } else { lockOverlay("paused-controls", action); } return true; } catch (e) { state.lastPlayer = action + ":error:" + (e && e.message ? e.message : String(e)); renderDiagnostics(); return false; } }
  function handleMediaKey(k) { var v = getPrimaryVideo(); if (!v) { state.lastPlayer = k + ":no-video"; renderDiagnostics(); return false; } if (k === "MediaPause") return pauseAndLockOverlay(k); if (k === "MediaPlay") return playAndUnlockOverlay(k); if (k === "MediaPlayPause") return v.paused ? playAndUnlockOverlay(k) : pauseAndLockOverlay(k); if (k === "MediaStop") { try { v.currentTime = 0; } catch (_e) {} return pauseAndLockOverlay(k); } if (k === "MediaFastForward") return seekVideo(k, SEEK_SECONDS, true); if (k === "MediaRewind") return seekVideo(k, -SEEK_SECONDS, true); return false; }
  function handleArrowSeek(k) { if (!hasPlayerVideo()) return false; if (state.overlayMode === "paused-controls") return false; if (k === "ArrowLeft") return seekVideo("ArrowLeft", -SEEK_SECONDS, true); if (k === "ArrowRight") return seekVideo("ArrowRight", SEEK_SECONDS, true); if (state.overlayMode === "seek-preview" && (k === "ArrowUp" || k === "ArrowDown")) { state.lastPlayer = k + ":seek-preview-kept"; renderDiagnostics(); return true; } return false; }
  function dispatchEscapeFallback() { var ev; try { ev = new KeyboardEvent("keydown", { key: "Escape", code: "Escape", bubbles: true, cancelable: true }); document.dispatchEvent(ev); return true; } catch (_e) { return false; } }
  function handleBack(event) { if (state.diagnosticsOpen) { state.diagnosticsOpen = false; state.lastBack = "closed-diagnostics"; renderDiagnostics(); consume(event); return true; } if (state.overlayLocked) { unlockOverlay("back-unlock-overlay"); state.lastBack = "unlocked-overlay"; renderDiagnostics(); consume(event); return true; } try { if (window.history && window.history.length > 1 && typeof window.history.back === "function") { window.history.back(); state.lastBack = "history-back"; renderDiagnostics(); consume(event); return true; } } catch (_e) {} if (dispatchEscapeFallback()) { state.lastBack = "escape-fallback"; renderDiagnostics(); consume(event); return true; } state.lastBack = "pass-through"; renderDiagnostics(); return false; }

  function handleKey(event) { var k = normalizeKey(event); state.lastKey = k; state.lastAction = "key:" + k; if (diagnosticsKeys[k]) { state.diagnosticsOpen = !state.diagnosticsOpen; renderDiagnostics(); consume(event); return true; } if (k === "Back") return handleBack(event); if (mediaKeys[k]) { if (handleMediaKey(k)) { consume(event); return true; } return false; } if (arrowKeys[k]) { if (handleArrowSeek(k)) { consume(event); return true; } if (state.overlayLocked && state.overlayMode === "paused-controls") { if (k === "ArrowLeft") movePlayerFocus("left"); if (k === "ArrowRight") movePlayerFocus("right"); if (k === "ArrowUp") movePlayerFocus("up"); if (k === "ArrowDown") movePlayerFocus("down"); consume(event); return true; } if (nonPlayerSpatial(k)) { consume(event); renderDiagnostics(); return true; } }
    if (state.overlayLocked && state.overlayMode === "paused-controls" && k === "Enter") { clickFocusedControl(); consume(event); return true; } state.lastIgnored = "pass-through:" + k; renderDiagnostics(); return false; }
  function init() { if (state.initialized) return; ensureStyles(); registerOptionalKeys(); document.addEventListener("keydown", handleKey, true); document.addEventListener("tizenhwkey", handleKey, true); window.addEventListener("keydown", handleKey, true); window.addEventListener("tizenhwkey", handleKey, true); state.initialized = true; window[NS] = api; renderDiagnostics(); }
  var api = { initialized: false, version: VERSION, getState: function () { return JSON.parse(JSON.stringify(state)); }, openDiagnostics: function () { state.diagnosticsOpen = true; renderDiagnostics(); }, closeDiagnostics: function () { state.diagnosticsOpen = false; renderDiagnostics(); }, toggleDiagnostics: function () { state.diagnosticsOpen = !state.diagnosticsOpen; renderDiagnostics(); }, lockOverlay: function () { return pauseAndLockOverlay("api-lock-overlay"); }, unlockOverlay: function () { unlockOverlay("api-unlock-overlay"); }, play: function () { return playAndUnlockOverlay("api-play"); }, pause: function () { return pauseAndLockOverlay("api-pause"); }, seekPreview: function (delta) { return seekVideo("api-seek-preview", Number(delta) || SEEK_SECONDS, true); } };
  window[NS] = api;
  if (document.readyState === "interactive" || document.readyState === "complete") init(); else document.addEventListener("DOMContentLoaded", init, false);
  api.initialized = true;
}(typeof window !== "undefined" ? window : this));
